services:
  db:
      image: postgres:14.2-alpine
      env_file:
        - .env  
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      ports:
        - 5432:5432


  api:
    build: .
    env_file:
      - .env 
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data: